import { useEffect, useMemo, useState } from 'react'
import { Activity, BarChart3, BookOpen, CheckCircle2, ChevronRight, CircleAlert, Clock3, Download, LayoutDashboard, Library, Menu, Plus, QrCode, Search, Settings2, UserRound, Users, X } from 'lucide-react'
import * as XLSX from 'xlsx'
import { api } from './api'
import AddBookModal from './components/AddBookModal'
import QrBook from './components/QrBook'
import QrScanner from './components/QrScanner'

const tabs = [{ id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'catalog', label: 'Book catalog', icon: Library }, { id: 'circulation', label: 'Circulation', icon: Activity }, { id: 'analytics', label: 'Analytics', icon: BarChart3 }]
const formatDate = (date) => date ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date)) : '—'
const daysOverdue = (date) => Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 86400000))

function StatCard({ label, value, detail, icon: Icon, tone }) { return <div className={`stat-card ${tone}`}><div className="stat-icon"><Icon size={18} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div> }
function StatusPill({ available }) { return <span className={`status-pill ${available ? 'available' : 'issued'}`}><span />{available ? 'Available' : 'Fully issued'}</span> }
function EmptyState({ label }) { return <div className="empty-state"><BookOpen size={22} /><p>{label}</p></div> }

export default function App() {
  const [tab, setTab] = useState('overview')
  const [books, setBooks] = useState([])
  const [transactions, setTransactions] = useState([])
  const [metrics, setMetrics] = useState({ totalBooks: 0, availableCopies: 0, issuedCopies: 0, overdueBooks: 0, issued: [] })
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All categories')
  const [status, setStatus] = useState('ALL')
  const [showAdd, setShowAdd] = useState(false)
  const [showScanner, setShowScanner] = useState(false)
  const [scanBook, setScanBook] = useState(null)
  const [toast, setToast] = useState('')
  const [loading, setLoading] = useState(true)

  const refresh = async () => { setLoading(true); try { const [bookData, txData, metricData] = await Promise.all([api.books({ search: query, category, status }), api.transactions(), api.analytics()]); setBooks(bookData); setTransactions(txData); setMetrics(metricData) } catch (error) { setToast(error.message) } finally { setLoading(false) } }
  useEffect(() => { refresh() }, [query, category, status])
  useEffect(() => { if (!toast) return; const timeout = setTimeout(() => setToast(''), 3500); return () => clearTimeout(timeout) }, [toast])

  const categories = useMemo(() => ['All categories', ...new Set(books.map((book) => book.category))], [books])
  const addBook = async (payload) => { try { await api.addBook(payload); setToast('Book added to the catalog.'); await refresh() } catch (error) { setToast(error.message); throw error } }
  const issue = async (bookId, borrowerName, borrowerId, dueDate) => { try { await api.issue({ bookId, borrowerName, borrowerId, dueDate }); setScanBook(null); setToast('Issue recorded.'); await refresh() } catch (error) { setToast(error.message) } }
  const returnBook = async (id) => { try { await api.returnBook(id); setToast('Return recorded.'); await refresh() } catch (error) { setToast(error.message) } }
  const handleScan = (value) => { const found = books.find((book) => book.isbn === value); setShowScanner(false); if (found) setScanBook(found); else setToast(`No book found for code ${value}.`) }
  const exportTransactions = () => { const rows = transactions.map((tx) => ({ 'Book Title': tx.bookTitle, Author: tx.bookAuthor, 'ISBN / Book ID': tx.bookIsbn, 'Borrower Name': tx.borrowerName, 'Borrower ID': tx.borrowerId, 'Issue Timestamp': tx.issueDate, 'Return Timestamp': tx.returnDate || '', 'Current Status': tx.status })); const sheet = XLSX.utils.json_to_sheet(rows); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, 'Transactions'); XLSX.writeFile(workbook, 'library-transactions.xlsx') }

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><BookOpen size={19} /></div><div><strong>leafline</strong><span>library services</span></div></div><div className="workspace-label">WORKSPACE</div><nav>{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? 'nav-item active' : 'nav-item'} onClick={() => setTab(id)}><Icon size={17} />{label}{id === 'circulation' && metrics.overdueBooks > 0 && <em>{metrics.overdueBooks}</em>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings2 size={17} />Settings</button><div className="account"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><span>Librarian</span></div><ChevronRight size={15} /></div></div></aside><main className="main-content"><header className="topbar"><button className="mobile-menu"><Menu size={19} /></button><div className="breadcrumb"><span>Library services</span><ChevronRight size={14} /><strong>{tabs.find((item) => item.id === tab)?.label}</strong></div><div className="top-actions"><button className="scan-button" onClick={() => setShowScanner(true)}><QrCode size={16} /> Scan a book</button><div className="notification"><CircleAlert size={18} /><span /></div><div className="mini-avatar">AM</div></div></header><section className="page-content"><div className="page-heading"><div><span className="eyebrow">MONDAY, SEPTEMBER 07, 2026</span><h1>{tab === 'overview' ? 'Good morning, Alex.' : tabs.find((item) => item.id === tab)?.label}</h1><p>{tab === 'overview' ? 'Here is what is happening across your library today.' : 'Keep your collection moving with a clear view of every record.'}</p></div><button className="primary-button" onClick={() => setShowAdd(true)}><Plus size={17} /> Add new book</button></div>{tab === 'overview' && <Overview metrics={metrics} issued={metrics.issued} onReturn={returnBook} onOpenCirculation={() => setTab('circulation')} />}{tab === 'catalog' && <Catalog books={books} categories={categories} query={query} setQuery={setQuery} category={category} setCategory={setCategory} status={status} setStatus={setStatus} loading={loading} onIssue={(book) => setScanBook(book)} />}{tab === 'circulation' && <Circulation transactions={transactions} onReturn={returnBook} onExport={exportTransactions} />}{tab === 'analytics' && <Analytics metrics={metrics} transactions={transactions} />}</section></main>{showAdd && <AddBookModal onClose={() => setShowAdd(false)} onSave={addBook} />}{showScanner && <QrScanner onClose={() => setShowScanner(false)} onScan={handleScan} />}{scanBook && <IssueModal book={scanBook} onClose={() => setScanBook(null)} onIssue={issue} />}{toast && <div className="toast"><CheckCircle2 size={17} />{toast}<button onClick={() => setToast('')}><X size={14} /></button></div>}</div>
}

function Overview({ metrics, issued, onReturn, onOpenCirculation }) { return <><div className="stats-grid"><StatCard label="Total books" value={metrics.totalBooks} detail="Titles in catalog" icon={BookOpen} tone="navy" /><StatCard label="Available copies" value={metrics.availableCopies} detail="Ready to borrow" icon={CheckCircle2} tone="mint" /><StatCard label="Issued copies" value={metrics.issuedCopies} detail="Currently on loan" icon={Users} tone="gold" /><StatCard label="Overdue books" value={metrics.overdueBooks} detail={metrics.overdueBooks ? 'Needs attention' : 'Everything on time'} icon={Clock3} tone="coral" /></div><div className="section-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Needs attention</span><h2>Active loans</h2></div><button className="link-button" onClick={onOpenCirculation}>View all <ChevronRight size={14} /></button></div>{issued.length === 0 ? <EmptyState label="No books are currently issued." /> : <div className="loan-list">{issued.slice(0, 5).map((tx) => <div className="loan-row" key={tx.id}><div className="book-cover">{tx.bookTitle?.slice(0, 2).toUpperCase()}</div><div className="loan-detail"><strong>{tx.bookTitle}</strong><span>{tx.borrowerName} · {tx.borrowerId}</span></div><div className={daysOverdue(tx.dueDate) ? 'due overdue' : 'due'}>{daysOverdue(tx.dueDate) ? `${daysOverdue(tx.dueDate)}d overdue` : `Due ${formatDate(tx.dueDate)}`}</div><button className="row-action" onClick={() => onReturn(tx.id)}>Return</button></div>)}</div>}</section><section className="panel accent-panel"><div className="panel-heading"><div><span className="eyebrow">This month</span><h2>Collection health</h2></div><BarChart3 size={19} /></div><div className="health-ring"><div><strong>{metrics.totalBooks ? Math.round((metrics.availableCopies / (metrics.availableCopies + metrics.issuedCopies || 1)) * 100) : 0}%</strong><span>available</span></div></div><div className="health-legend"><span><i className="dot mint-dot" />Available <strong>{metrics.availableCopies}</strong></span><span><i className="dot gold-dot" />Issued <strong>{metrics.issuedCopies}</strong></span></div></section></div></> }

function Catalog({ books, categories, query, setQuery, category, setCategory, status, setStatus, loading, onIssue }) { return <section className="panel catalog-panel"><div className="panel-heading"><div><span className="eyebrow">Collection</span><h2>Book catalog</h2></div><span className="record-count">{books.length} records</span></div><div className="filters"><div className="search-input"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search title, author, ISBN..." /></div><select value={category} onChange={(e) => setCategory(e.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="AVAILABLE">Available</option><option value="ISSUED">Fully issued</option></select></div>{loading ? <EmptyState label="Loading catalog..." /> : books.length === 0 ? <EmptyState label="No books match these filters." /> : <div className="table-scroll"><table><thead><tr><th>Book</th><th>Author</th><th>Category</th><th>Availability</th><th>Status</th><th /></tr></thead><tbody>{books.map((book) => <tr key={book.id}><td><div className="table-book"><div className="book-cover small">{book.title.slice(0, 2).toUpperCase()}</div><div><strong>{book.title}</strong><span>{book.isbn}</span></div></div></td><td>{book.author}</td><td><span className="category-tag">{book.category}</span></td><td><strong>{book.availableCopies}</strong> / {book.totalCopies}</td><td><StatusPill available={book.availableCopies > 0} /></td><td><button className="row-action" disabled={!book.availableCopies} onClick={() => onIssue(book)}>Issue</button></td></tr>)}</tbody></table></div>}</section> }

function Circulation({ transactions, onReturn, onExport }) { return <section className="panel catalog-panel"><div className="panel-heading"><div><span className="eyebrow">Record history</span><h2>Circulation activity</h2></div><button className="outline-button" onClick={onExport}><Download size={15} /> Export spreadsheet</button></div><div className="table-scroll"><table><thead><tr><th>Book</th><th>Borrower</th><th>Issued</th><th>Due</th><th>Returned</th><th>Status</th><th /></tr></thead><tbody>{transactions.map((tx) => <tr key={tx.id}><td><strong>{tx.bookTitle}</strong><span className="table-sub">{tx.bookIsbn}</span></td><td><strong>{tx.borrowerName}</strong><span className="table-sub">{tx.borrowerId}</span></td><td>{formatDate(tx.issueDate)}</td><td className={tx.status === 'ISSUED' && daysOverdue(tx.dueDate) ? 'overdue' : ''}>{formatDate(tx.dueDate)}{tx.status === 'ISSUED' && daysOverdue(tx.dueDate) ? ` · ${daysOverdue(tx.dueDate)}d late` : ''}</td><td>{formatDate(tx.returnDate)}</td><td><span className={`status-pill ${tx.status === 'RETURNED' ? 'available' : 'issued'}`}><span />{tx.status === 'RETURNED' ? 'Returned' : 'Issued'}</span></td><td>{tx.status === 'ISSUED' && <button className="row-action" onClick={() => onReturn(tx.id)}>Return</button>}</td></tr>)}</tbody></table>{!transactions.length && <EmptyState label="No transaction history yet." />}</div></section> }

function Analytics({ metrics, transactions }) { const returned = transactions.filter((tx) => tx.status === 'RETURNED').length; return <div className="analytics-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">Operational snapshot</span><h2>Collection performance</h2></div></div><div className="bars"><div className="bar-group"><div className="bar available-bar" style={{ height: `${Math.max(8, metrics.availableCopies * 8)}px` }} /><span>Available</span><strong>{metrics.availableCopies}</strong></div><div className="bar-group"><div className="bar issued-bar" style={{ height: `${Math.max(8, metrics.issuedCopies * 8)}px` }} /><span>Issued</span><strong>{metrics.issuedCopies}</strong></div><div className="bar-group"><div className="bar returned-bar" style={{ height: `${Math.max(8, returned * 8)}px` }} /><span>Returned</span><strong>{returned}</strong></div></div></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Live queue</span><h2>Overdue tracker</h2></div><span className="alert-count">{metrics.overdueBooks} overdue</span></div>{metrics.issued.filter((tx) => daysOverdue(tx.dueDate)).map((tx) => <div className="overdue-row" key={tx.id}><div className="alert-icon"><Clock3 size={16} /></div><div><strong>{tx.bookTitle}</strong><span>{tx.borrowerName} · due {formatDate(tx.dueDate)}</span></div><b>{daysOverdue(tx.dueDate)} days</b></div>)}{!metrics.issued.some((tx) => daysOverdue(tx.dueDate)) && <EmptyState label="No overdue books. Nice work." />}</section></div> }

function IssueModal({ book, onClose, onIssue }) { const [borrowerName, setBorrowerName] = useState(''); const [borrowerId, setBorrowerId] = useState(''); const [dueDate, setDueDate] = useState(new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10)); return <div className="scanner-overlay"><form className="form-modal" onSubmit={(e) => { e.preventDefault(); onIssue(book.id, borrowerName, borrowerId, dueDate) }}><div className="modal-head"><div><span className="eyebrow"><QrCode size={14} /> Issue book</span><h2>{book.title}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18} /></button></div><div className="issue-preview"><div className="book-cover">{book.title.slice(0, 2).toUpperCase()}</div><div><strong>{book.author}</strong><span>{book.availableCopies} copies available · {book.isbn}</span></div></div><div className="form-grid"><label>Borrower name<input required value={borrowerName} onChange={(e) => setBorrowerName(e.target.value)} placeholder="Full name" /></label><label>Borrower ID<input required value={borrowerId} onChange={(e) => setBorrowerId(e.target.value)} placeholder="e.g. STU-2048" /></label><label>Due date<input required type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label></div><button className="primary-button full" disabled={!book.availableCopies}>Confirm issue</button></form></div> }
